version: 2.1

orbs:
  rn: react-native-community/react-native@1.1.0

defaults: &defaults
  docker:
    - image: circleci/node:10

jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .

  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
        name: Run Tests
        command: yarn test

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - rn/yarn_install
      - run:
          name: Publish to NPM
          command: yarn run release

workflows:
  version: 2
  ci:
    jobs:
      - checkout_code
      - test:
          requires:
            - checkout_code
      - publish:
          requires:
            - test
          filters:
            branches:
              only: master
